apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  #namespace: cockroachdb
  labels:
    app: cockroachdb-client
spec:
  containers:
  - name: cockroachdb-client
    image: cockroachdb/cockroach:v22.2.6
    command:
    - sleep
    - "2147483648" # 2^31
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
  volumes:
  - name: client-certs
    secret:
      secretName: cockroachdb.client
      defaultMode: 256
